name: Generate Ros

on:
  workflow_dispatch:
    inputs:
      software_id:
        description: 'Enter the Software ID'
        required: true
        type: string

jobs:
  generate-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies to install"

      - name: Run license.py and Save Output
        run: |
          python3 license.py licgenros ${{ inputs.software_id }} 9DBC845E9018537810FDAE62824322EEE1B12BAD81FCA28EC295FB397C61CE0B > ${{ inputs.software_id }}.txt
          cat ${{ inputs.software_id }}.txt  # Display the license in logs for debugging

      - name: Upload License Key as Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "license-release-${{ github.run_id }}" ${{ inputs.software_id }}.txt --title "License for ${{ inputs.software_id }}" --notes "Generated license for ${{ inputs.software_id }}"
